SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS DNA_GENE_CASSETTE_ITEM;
DROP TABLE IF EXISTS DNA_GENE_CASSETTE;
DROP TABLE IF EXISTS DNA_GENE_FREQUENCY;
DROP TABLE IF EXISTS DNA_GENE_LOCI;
DROP TABLE IF EXISTS DNA_STR_IMPORT_ITEM;
DROP TABLE IF EXISTS DNA_STR_IMPORT;




/* Create Tables */

CREATE TABLE DNA_GENE_CASSETTE
(
	ID VARCHAR(64) NOT NULL,
	NAME VARCHAR(255),
	SEQ INT,
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
);


CREATE TABLE DNA_GENE_CASSETTE_ITEM
(
	ID VARCHAR(64) NOT NULL,
	CASSETTE_ID VARCHAR(64) NOT NULL,
	LOCI_ID VARCHAR(64) NOT NULL,
	PRIMARY KEY (ID)
);


-- 等位基因频率
CREATE TABLE DNA_GENE_FREQUENCY
(
	ID VARCHAR(64) NOT NULL,
	LOCI_ID VARCHAR(64) NOT NULL,
	VALUE FLOAT,
	PROBABILITY REAL,
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '等位基因频率';


CREATE TABLE DNA_GENE_LOCI
(
	ID VARCHAR(64) NOT NULL,
	NAME VARCHAR(255),
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
);


CREATE TABLE DNA_STR_IMPORT
(
	ID VARCHAR(64) NOT NULL,
	REGISTER_ID VARCHAR(64),
	STATUS INT,
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
);


CREATE TABLE DNA_STR_IMPORT_ITEM
(
	ID VARCHAR(64) NOT NULL,
	IMPORT_ID VARCHAR(64) NOT NULL,
	GENE_LOCI VARCHAR(255),
	MATERIAL_CODE VARCHAR(255),
	VALUE VARCHAR(255),
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE DNA_GENE_CASSETTE_ITEM
	ADD FOREIGN KEY (CASSETTE_ID)
	REFERENCES DNA_GENE_CASSETTE (ID)
;


ALTER TABLE DNA_GENE_CASSETTE_ITEM
	ADD FOREIGN KEY (LOCI_ID)
	REFERENCES DNA_GENE_LOCI (ID)
;


ALTER TABLE DNA_GENE_FREQUENCY
	ADD FOREIGN KEY (LOCI_ID)
	REFERENCES DNA_GENE_LOCI (ID)
;


ALTER TABLE DNA_STR_IMPORT_ITEM
	ADD FOREIGN KEY (IMPORT_ID)
	REFERENCES DNA_STR_IMPORT (ID)
;



