SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS ENTRUST_EXPERT_OPINION;




/* Create Tables */

CREATE TABLE ENTRUST_EXPERT_OPINION
(
	ID VARCHAR(64) NOT NULL,
	REGISTER_ID VARCHAR(64),
	ROLE_NAME CHAR,
	OPINION TEXT,
	VERSION VARCHAR(255),
	APPRAISER VARCHAR(64),
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
);



