SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS SYS_CODE_RULE_ITEM;
DROP TABLE IF EXISTS SYS_CODE_RULE;
DROP TABLE IF EXISTS SYS_SEQUENCE;




/* Create Tables */

-- 编码生成规则
CREATE TABLE SYS_CODE_RULE
(
	ID VARCHAR(64) NOT NULL,
	-- 编码
	CODE VARCHAR(255) COMMENT '编码',
	-- 名称
	NAME VARCHAR(255) COMMENT '名称',
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '编码生成规则';


-- 编码生成规则明细
CREATE TABLE SYS_CODE_RULE_ITEM
(
	ID VARCHAR(64) NOT NULL,
	RULE_ID VARCHAR(64) NOT NULL,
	-- 段
	SEQ INT COMMENT '段',
	-- 字段类型
	CODE_TYPE INT COMMENT '字段类型',
	-- 模式
	PATTERN VARCHAR(255) COMMENT '模式',
	-- 数值长度
	 DIGITAL_LENGTH INT COMMENT '数值长度',
	SEQUENCE_ID VARCHAR(64),
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '编码生成规则明细';


-- 序列
CREATE TABLE SYS_SEQUENCE
(
	ID VARCHAR(64) NOT NULL,
	-- 名称
	NAME VARCHAR(255) COMMENT '名称',
	-- 开始
	START INT COMMENT '开始',
	-- 当前值
	CURRENT BIGINT COMMENT '当前值',
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '序列';



/* Create Foreign Keys */

ALTER TABLE SYS_CODE_RULE_ITEM
	ADD FOREIGN KEY (RULE_ID)
	REFERENCES SYS_CODE_RULE (ID)
;



