SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS CLINIC_CHECKED;
DROP TABLE IF EXISTS CLINIC_REGISTER;




/* Create Tables */

-- 被检人信息
CREATE TABLE CLINIC_CHECKED
(
	REGISTER_ID VARCHAR(64) COMMENT 'register_id',
	ID VARCHAR(64) NOT NULL COMMENT 'id',
	NAME VARCHAR(255) COMMENT '名字',
	IDNUMBER VARCHAR(255) COMMENT '身份证号',
	SEX VARCHAR(255) COMMENT '性别',
	NATIVE_PLACE VARCHAR(255) COMMENT '籍贯',
	ADDRESS VARCHAR(255) COMMENT '住址',
	OCCUPATION VARCHAR(255) COMMENT '职业',
	WORK_UNITS VARCHAR(255) COMMENT '工作单位',
	EDUCATION VARCHAR(255) COMMENT '文化程度',
	PHONE VARCHAR(245) COMMENT '联系电话',
	TIME DATE COMMENT '受伤时间',
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID)
) COMMENT = '被检人信息';


-- 委托登记
CREATE TABLE CLINIC_REGISTER
(
	ID VARCHAR(64) NOT NULL COMMENT 'id',
	-- 编码
	CODE VARCHAR(255) COMMENT '编码',
	-- 委托人
	CLIENT_NAME VARCHAR(255) COMMENT '委托人',
	-- 委托人电话
	CLIENT_TEL VARCHAR(255) COMMENT '委托人电话',
	-- 委托收件人
	CLIENT_RECEIVER VARCHAR(255) COMMENT '委托收件人',
	-- 委托人邮箱
	CLIENT_EMAIL VARCHAR(255) COMMENT '委托人邮箱',
	-- 委托人传真
	CLIENT_FAX VARCHAR(255) COMMENT '委托人传真',
	-- 委托人邮编
	CLIENT_ZIPCODE VARCHAR(255) COMMENT '委托人邮编',
	-- 委托人区域
	CLIENT_AREA VARCHAR(1000) COMMENT '委托人区域',
	-- 委托人地址
	CLIENT_ADDRESS VARCHAR(1000) COMMENT '委托人地址',
	-- 送检人(机构)
	AGENT_NAME VARCHAR(255) COMMENT '送检人(机构)',
	-- 送检人电话
	AGENT_TEL VARCHAR(255) COMMENT '送检人电话',
	-- 受理人
	SERVER_NAME VARCHAR(255) COMMENT '受理人',
	-- 受理机构
	SERVER_ORG_ID VARCHAR(255) COMMENT '受理机构',
	-- 报告传递方式
	SEND_MODE CHAR COMMENT '报告传递方式',
	-- 专业
	SPECIALTY CHAR COMMENT '专业',
	-- 类型
	TYPE CHAR COMMENT '类型',
	-- 鉴定材料
	MATERIAL VARCHAR(255) COMMENT '鉴定材料',
	-- 检材处理
	MATERIAL_DISPOSE VARCHAR(255) COMMENT '检材处理',
	-- 时限结果
	TIME_LIMIT_RESULT CHAR COMMENT '时限结果',
	-- 时间报告
	TIME_LIMIT_REPORT CHAR COMMENT '时间报告',
	-- 标准费用
	STANDARD_FEE REAL COMMENT '标准费用',
	-- 特殊费用
	SPECIAL_FEE REAL COMMENT '特殊费用',
	-- 合计费用
	TOTAL_FEE REAL COMMENT '合计费用',
	-- 鉴定项
	APPRAISAL_ITEM VARCHAR(255) COMMENT '鉴定项',
	-- 鉴定人回避
	CLIENT_AVOID BIT(1) COMMENT '鉴定人回避',
	-- 授权客服人员通知
	AUTHORIZE_NOTIFICATION BIT(1) COMMENT '授权客服人员通知',
	STATUS CHAR COMMENT '状态',
	-- 流程id
	PROC_INS_ID VARCHAR(255) COMMENT '流程id',
	-- 创建者
	CREATE_BY VARCHAR(64) COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME COMMENT '创建时间',
	-- 修改者
	UPDATE_BY VARCHAR(64) COMMENT '修改者',
	-- 修改时间
	UPDATE_DATE DATETIME COMMENT '修改时间',
	-- 备注
	REMARKS VARCHAR(255) COMMENT '备注',
	-- 删除标记
	DEL_FLAG CHAR COMMENT '删除标记',
	PRIMARY KEY (ID),
	UNIQUE (CODE)
) COMMENT = '委托登记';



/* Create Foreign Keys */

ALTER TABLE CLINIC_CHECKED
	ADD FOREIGN KEY (REGISTER_ID)
	REFERENCES CLINIC_REGISTER (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



